// Code generated by go generate; DO NOT EDIT.
package main
const indexHTMLTemplate = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Mailimage</title>
  <style>
    body {
      margin: 0;
    }

    main section {
      width: 300px;
      height: 300px;
      overflow: hidden;
      border: 1px solid;
      text-align: center;
      margin: 5px;
      float: left;
      font-family: "ABeeZee", sans-serif;
    }
    main section h1 {
      font-size: 0.9em;
      font-family: "Sarala", sans-serif;
    }
    main section img {
      display: block;
      margin: auto;
      object-fit: contain;
    }
  </style>
</head>
<body>
  <main>
    {{ range . }}
      <section>
        <h1>{{ .Subject }}</h1>
        {{ .From }} {{ .Created }}
        <a href="image/{{ .ID }}{{ .Extension }}" target="_blank">
          <img src="thumbnail/{{ .ID }}.jpg" alt="" width="250px" height="200px">
        </a>
        {{ .Text }}
      </section>
    {{ else }}
      Keine Bilder vorhanden.
    {{ end }}
  </main>
</body>
</html>
`
