package main

import (
	"io/ioutil"
	"log"
	"os"
	"text/template"
)

var packageTemplate = template.Must(template.New("").Parse(
	"// Code generated by go generate; DO NOT EDIT.\npackage mailimage\n\nconst indexHTMLTemplate = `{{ . }}`\n",
))

func main() {
	in, err := ioutil.ReadFile("index.html")
	if err != nil {
		log.Fatalf("can not open file: %v", err)
	}

	out, err := os.Create("index.html.go")
	if err != nil {
		log.Fatalf("can not write index.html.go: %v", err)
	}

	if err := packageTemplate.Execute(out, string(in)); err != nil {
		log.Fatalf("can not execute template: %v", err)
	}
}
